# This is the base configuration file, which stores the settings used previously.

title = "Base Configuration"

[files]
full_config_path = ".testing_base_config.toml" # The location of the primary configuration file.
